config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :usuarios, 
    controllers: { sessions: "usuarios/sessions", registrations: "usuarios/registrations" }, 
    path: "", 
    path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}

  devise_scope :usuario do
    get "perfil_opciones", to: "usuarios/registrations#opciones", as: "perfil_opciones"
    get "joyas_compradas", to: "usuarios/registrations#joyas_compradas", as: "joyas_compradas"
  end

  root "hello#index"
  get "registrarse", to: "usuarios#nuevo"
  post "usuario", to: "usuarios#create"
  get "perfil/:id", to: "usuarios#perfil", as: "perfil"
  patch "perfil/:id", to: "usuarios#update"
  delete "perfil/:id", to: "usuarios#destroy", as: "eliminar_perfil"
  delete "publicacions/:id/eliminar", to: "publicacions#destroy", as: "eliminar_publicacion"
  get "publicacions/:id/eliminar", to: "publicacions#confirmar_eliminacion", as: "confirmar_eliminacion"
  patch "publicacions/:id/eliminar", to: "publicacions#destroy", as: "eliminar_confirmacion_publicacion_path"
  
  # resources :publicacions
  resources :publicacions do
    resources :comentarios, only: [:create, :destroy]
  end
  resources :publicacions do
    resources :joyas, only: [:create, :destroy, :update]
  end
  resources :chatrooms
  resources :chatrooms do
    resources :mensajes, only: [:create, :destroy]
  end

  get "crear_joya", to: "joyas#nueva_joya"
  post "joya", to: "joyas#create"
  get "joya_creada/:id", to: "joyas#joya_creada", as: "joya_creada"
  patch "joya_creada/:id", to: "joyas#update"
  delete "joya_creada/:id", to: "joyas#destroy", as: "eliminar_joya_creada"
  get "/carrito", to: "carrito#index", as: "carrito_path"
  get "generar_pdf_carrito", to: "carrito#generar_pdf_carrito", as: "generar_pdf_carrito"

  post "solicitud_compra", to: "joyas#solicitud_compra", as: "solicitud_compra"
  patch "joyas/:id/solicitud_compra", to: "joyas#solicitud_compra", as: "solicitud_compra_joya"
  get "solicitudes_compra", to: "publicacions#solicitudes_compra", as: "solicitudes_compra"
  resources :joyas do
    member do
      patch :aceptar_solicitud
      patch :rechazar_solicitud
    end
  end
  post "pagar", to: "carrito#pagar", as: "pagar"

end

app/controllers/carrito_controller.rb
# frozen_string_literal: true
class CarritoController < ApplicationController
  before_action :set_publicacion, only: [:create, :destroy]
  def index
    unless current_usuario
      redirect_to(root_path, alert: "Debes registrarte o iniciar sesión para solicitar materiales")
      return
    end
    @joyas = current_usuario.joyas.where.not(estado: "Vendido")
  end

  def pagar
    @joyas = current_usuario.joyas
    @user = current_usuario

    @list = List.create(usuario_id: @usuario.id)
    @joyas.update(list_id: @list.id)
    @joyas.where(estado: "Aceptado").update_all(estado: "Vendido")
    @joyas.where(estado: "Rechazado").destroy_all
    render("pagar")
  end

end

app/helpers/carrito_helper.rb
# frozen_string_literal: true
module CarritoHelper
end

app/views/carrito/index.html.erb
<%= stylesheet_link_tag 'carrito-index', media: 'all', 'data-turbolinks-track': 'reload' %>
<h1 class="titulo has-text-centered is-size-1">Materiales</h1>

<section class="section">
  <div class="container">
    <% if @joyas.any? %>
      <table class="table is-fullwidth">
        <thead>
          <tr>
            <th>Material</th>
            <th>Cantidad</th>
            <th colspan="4"></th>
          </tr>
        </thead>
        <tbody>
          <% precio_total = 0 %>
          <% @joyas.each do |joya| %>
            <tr>
              <td><%= joya.publicacion.nombre %></td>
              <td>
                <% if joya.estado == "No solicitado" %>
                  <%= form_with(model: joya, url: [joya.publicacion, joya], method: :patch, local: true) do |form| %>
                  <%= form.number_field :cantidad, value: joya.cantidad, class: 'input', style: 'max-width: 50px;' %> <%= joya.publicacion.unidad %> <br>
                  <%= form.submit 'A', class: 'button is-link is-light' %>
                  <% end %>
                <% else %>
                  <%= joya.cantidad %> <%= joya.publicacion.unidad %>
                <% end %>
              </td>
              <td>
                <%= button_to "E", [joya.publicacion, joya], method: :delete, data: { confirm: 'Estás seguro?' }, class: "button is-danger is-light" %>
              </td>
              <td>
                <% if joya.estado == "No solicitado" %>
                <%= button_to "SM", solicitud_compra_joya_path(joya), method: :patch, class: "button is-primary is-light" %>
                <% elsif joya.estado == "Aceptado"%>
                <div class="aceptado-rectangulo">Aceptado</div>
                <% elsif joya.estado == "Rechazado"%>
                <div class="rechazado-rectangulo">Rechazado</div>
                <% elsif joya.estado == "Pendiente"%>
                <div class="solicitado-rectangulo">Solicitado</div>
                <% end %>
              </td>
            </tr>
          <% end %>
        </tbody>
        <tfoot>
          <tr>
            <td colspan="4" class="has-text-right"><strong>Total:</strong></td>
            <td>$<%= precio_total %></td>
          </tr>
          <td>
            <% if @joyas.any? { |joya| joya.estado != "Aceptado" && joya.estado != "Rechazado" } %>
              <div class="mensaje-espera">
                Debes esperar a que se resuelvan todas las solicitudes para pagar.
              </div>
            <% else %>
              <%= button_to "Ir a pagar", pagar_path, method: :post, class: "button is-primary is-light" %>
            <% end %>
          </td>
        </tfoot>
      </table>
    <% else %>
      <h2 class="subtitulo has-text-centered is-size-3">Tu carrito está vacío!</h2>
    <% end %>
</div>
</section>

app/views/carrito/pagar.html.erb
<%= stylesheet_link_tag 'resumen-pago', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="resumen-container">
  <h1 class="titulo has-text-centered is-size-1">Confirmación de Pago</h1>

  <p>Tu pago ha sido procesado correctamente.</p>
  <p>Los elementos del carrito han sido eliminados y las joyas han sido marcadas como vendidas.</p>

  <h2 class="subtitulo has-text-centered is-size-3">Resumen de la compra</h2>

  <table class="resumen-table">
    <thead>
      <tr>
        <th>Joya</th>
        <th>Cantidad</th>
        <th>Precio unitario</th>
        <th>Precio total</th>
      </tr>
    </thead>
    <tbody>
      <% @precio_total = 0 %>
      <% @joyas.each do |joya| %>
        <% precio_total_producto = joya.cantidad * joya.publicacion.precio %>
        <% if joya.estado == "Vendido" %>
          <% @precio_total += precio_total_producto %>
        <% end %>
        <tr>
          <td><%= joya.publicacion.nombre %></td>
          <td><%= joya.cantidad %></td>
          <td>$<%= joya.publicacion.precio %></td>
          <td>$<%= precio_total_producto %></td>
        </tr>
      <% end %>
      <tr>
        <td colspan="3" class="has-text-right"><strong>Total:</strong></td>
        <td>$<%= @precio_total %></td>
      </tr>
    </tbody>
  </table>

  <div class="button-container">
    <%= link_to 'Volver a las Publicaciones', publicacions_path, class: 'button is-link' %>
  </div>

  <p>¡Gracias por tu compra!</p>
</div>