config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :usuarios, 
    controllers: { sessions: "usuarios/sessions", registrations: "usuarios/registrations" }, 
    path: "", 
    path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}

  devise_scope :usuario do
    get "perfil_opciones", to: "usuarios/registrations#opciones", as: "perfil_opciones"
    get "joyas_compradas", to: "usuarios/registrations#joyas_compradas", as: "joyas_compradas"
  end

  root "hello#index"
  get "registrarse", to: "usuarios#nuevo"
  post "usuario", to: "usuarios#create"
  get "perfil/:id", to: "usuarios#perfil", as: "perfil"
  patch "perfil/:id", to: "usuarios#update"
  delete "perfil/:id", to: "usuarios#destroy", as: "eliminar_perfil"
  delete "publicacions/:id/eliminar", to: "publicacions#destroy", as: "eliminar_publicacion"
  get "publicacions/:id/eliminar", to: "publicacions#confirmar_eliminacion", as: "confirmar_eliminacion"
  patch "publicacions/:id/eliminar", to: "publicacions#destroy", as: "eliminar_confirmacion_publicacion_path"
  
  # resources :publicacions
  resources :publicacions do
    resources :comentarios, only: [:create, :destroy]
  end
  resources :publicacions do
    resources :joyas, only: [:create, :destroy, :update]
  end
  resources :chatrooms
  resources :chatrooms do
    resources :mensajes, only: [:create, :destroy]
  end

  get "crear_joya", to: "joyas#nueva_joya"
  post "joya", to: "joyas#create"
  get "joya_creada/:id", to: "joyas#joya_creada", as: "joya_creada"
  patch "joya_creada/:id", to: "joyas#update"
  delete "joya_creada/:id", to: "joyas#destroy", as: "eliminar_joya_creada"
  get "/carrito", to: "carrito#index", as: "carrito_path"
  get "generar_pdf_carrito", to: "carrito#generar_pdf_carrito", as: "generar_pdf_carrito"

  post "solicitud_compra", to: "joyas#solicitud_compra", as: "solicitud_compra"
  patch "joyas/:id/solicitud_compra", to: "joyas#solicitud_compra", as: "solicitud_compra_joya"
  get "solicitudes_compra", to: "publicacions#solicitudes_compra", as: "solicitudes_compra"
  resources :joyas do
    member do
      patch :aceptar_solicitud
      patch :rechazar_solicitud
    end
  end
  post "pagar", to: "carrito#pagar", as: "pagar"

end

app/models/chatroom.rb
# frozen_string_literal: true
class Chatroom < ApplicationRecord
  has_many :usuarios, through: :mensajes
  has_many :mensajes, dependent: :destroy
  validates :motivo, :remitente, :creador, :estado, presence: true
  validates :soporte, inclusion: { in: [true, false] }
end

app/controllers/chatrooms_controller.rb
# frozen_string_literal: true
class ChatroomsController < ApplicationController
  
  def index
    unless current_usuario
      redirect_to(root_path, alert: "No puedes ver chats como invitado, regístrate!") unless current_usuario
        return
    end
    @chatrooms_creados = Chatroom.where(creador: current_usuario.nombre_usuario)
    @chatrooms_entrantes = Chatroom.where(remitente: current_usuario.nombre_usuario)
  end

  def show
    @chatroom = Chatroom.find(params[:id])
    @mensaje= Mensaje.new 
    @mensajes = @chatroom.mensajes
  end
  
  def new
    redirect_to(root_path, alert: "Debes estar registrado para crear chats.") unless current_usuario
      @chatroom = Chatroom.new
      if params[:seller].present?
        @user = Usuario.find_by(nombre_usuario: params[:seller])
      else
        @user = Usuario.where(tipo_usuario: :admin).order("RANDOM()").limit(1).first
      end

      if params[:support].present?
        @tipo_chat = params[:support]
      else
        @tipo_chat = true
      end
      
      if @user.nil?
        redirect_to(chatrooms_path, alert: "No existen administradores actualmente.")
      end
  end

  def update
    @chatroom = Chatroom.find(params[:id])
    if @chatroom.update(estado: "Cerrado")
      redirect_to(chatrooms_path, notice: "Conversación cerrada")
    else
      redirect_to(chatrooms_path, alert: "Este chat no se pudo cerrar!")
    end
  end
  
  def create
    @chatroom = Chatroom.new(chatroom_params)

    if @chatroom.save
      redirect_to(@chatroom, notice: "Chatroom was successfully created.")
    else
      render(:new)
    end
  end
  
    private
  
  def chatroom_params
    params.require(:chatroom).permit(:motivo, :soporte, :remitente, :creador, :estado)
  end
end

app/helpers/chatrooms_helper.rb
# frozen_string_literal: true
module ChatroomsHelper
end

app/views/chatrooms/index.html.erb
<%= stylesheet_link_tag 'chatrooms-index', media: 'all', 'data-turbolinks-track': 'reload' %>
<section class="section">
  <div class="container">
    <h1 class="title">Conversaciones</h1>

    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th>Motivo</th>
          <th>Tipo</th>
          <th>Remitente</th>
          <th>Estado</th>
          <th colspan="2"></th>
        </tr>
      </thead>

      <tbody>
        <% @chatrooms_creados.each do |chatroom| %>
          <tr>
            <td><%= chatroom.motivo %></td>
            <% if chatroom.soporte %>
              <td> Soporte </td>
            <% else %>
              <td> Ventas </td>
            <% end %>
            <td><%= chatroom.remitente %></td>
            <td><%= chatroom.estado %></td>
            <% if chatroom.estado == 'Abierto' && chatroom.soporte %>
              <td><%= link_to 'Entrar', chatroom_path(chatroom), class: 'button is-info is-small' %></td>
              <td><%= link_to 'Cerrar', edit_chatroom_path(chatroom), class: 'button is-link is-small' %></td> 
            <% else %> 
              <td><%= link_to 'Entrar', chatroom_path(chatroom), class: 'button is-info is-small' %></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <%= link_to 'Contactar al soporte', new_chatroom_path, class: 'button is-link' %>
  </div>
</section>

<section class="section">
  <div class="container">
    <h1 class="title">Conversaciones Entrantes</h1>

    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th>Motivo</th>
          <th>Tipo</th>
          <th>Creador</th>
          <th>Estado</th>
          <th></th>
        </tr>
      </thead>

      <tbody>
        <% @chatrooms_entrantes.each do |chatroom| %>
          <tr>
            <td><%= chatroom.motivo %></td>
            <% if chatroom.soporte %>
              <td> Soporte </td>
            <% else %>
              <td> Ventas </td>
            <% end %>
            <td><%= chatroom.creador %></td>
            <td><%= chatroom.estado %></td>
            <td><%= link_to 'Entrar', chatroom_path(chatroom), class: 'button is-info is-small' %></td>
          </tr>
        <% end %>
      </tbody>
    </table>
  </div>
</section>

app/views/chatrooms/new.html.erb
<%= stylesheet_link_tag 'register-new', media: 'all', 'data-turbolinks-track': 'reload' %>
<h1 class="titulo has-text-centered is-size-1">Crear Nueva Conversación</h1>
<%= form_with(model: @chatroom, url: { action: "create" }, local: true) do |form| %>
  <% if @chatroom.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@chatroom.errors.count, "error") %> impidieron hacer esta sala de chat:</h2>

      <ul>
        <% @chatroom.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Motivo %><br>
    <%= form.text_field :motivo, required: true %>
  </div>
  <%= form.hidden_field :soporte, value: @tipo_chat %>
  <%= form.hidden_field :remitente, value: @user.nombre_usuario %>
  <%= form.hidden_field :creador, value: current_usuario.nombre_usuario %>
  <%= form.hidden_field :estado, value: 'Abierto' %>

  <div class="actions">
    <%= button_tag(type: 'submit', class: 'button is-link') do %>
      Crear
    <% end %>
  </div>
<% end %>

<br>

<div class="links-container">
  <%= link_to 'Regresar a la Lista de Conversaciones', chatrooms_path %>
</div>

app/views/chatrooms/show.html.erb
<%= stylesheet_link_tag 'chatrooms-show', media: 'all', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">
<h1 class="titulo has-text-centered is-size-1"><%= @chatroom.motivo %></h1>
<h1 class="titulo has-text-centered is-size-2"><%= @chatroom.estado %></h1>

<div class="links-container">
  <% if (((@chatroom.estado == 'Abierto') && current_usuario.admin?) || ((@chatroom.estado == 'Abierto') && (current_usuario.nombre_usuario == @chatroom.creador))) && (@chatroom.soporte) %>
    <%= form_with(model: @chatroom, url: [@chatroom], method: :patch, local: true) do |form| %>
      <%= form.submit 'Cerrar Conversación', class: 'button is-link' %>
    <% end %>
  <% end %>
  <%= link_to 'Regresar al Listado de Conversaciones', chatrooms_path %>
</div>
<div class="container-comentarios">
  <div class="box">
    <% @mensajes.each do |mensaje| %>
      <div class="comentario">
        <p class="comentario-info">
          Autor: <%= (mensaje.usuario).nombre_usuario %><br>
          Fecha: <%= mensaje.created_at.strftime("%d/%m/%Y %H:%M") %>
        </p>
        <p class="comentario-contenido"><%= mensaje.body %></p>
      </div>
    <% end %>

    <div class="comentario-form">
      <% if @chatroom.estado == 'Abierto' %>
        <%= form_with(model: @mensaje, url: chatroom_mensajes_path(@chatroom), local: true) do |form| %>
          <%= form.text_area :body, placeholder: "Escribe aquí tu comentario" %>
          <%= form.hidden_field :usuario_id, value: current_usuario.id %>
          <%= form.submit "Enviar", class: "button is-link" %>
        <% end %>
      <% else %>
        <%= content_tag(:strong,'Este chat no puede ser respondido ya que está cerrado') %>
      <% end %>
    </div>
  </div>
</div>