config/routes.rb
# frozen_string_literal: true
Rails.application.routes.draw do
  devise_for :usuarios, 
    controllers: { sessions: "usuarios/sessions", registrations: "usuarios/registrations" }, 
    path: "", 
    path_names: {sign_in: "login", sign_out: "logout", sign_up: "register"}

  devise_scope :usuario do
    get "perfil_opciones", to: "usuarios/registrations#opciones", as: "perfil_opciones"
    get "joyas_compradas", to: "usuarios/registrations#joyas_compradas", as: "joyas_compradas"
  end

  root "hello#index"
  get "registrarse", to: "usuarios#nuevo"
  post "usuario", to: "usuarios#create"
  get "perfil/:id", to: "usuarios#perfil", as: "perfil"
  patch "perfil/:id", to: "usuarios#update"
  delete "perfil/:id", to: "usuarios#destroy", as: "eliminar_perfil"
  delete "publicacions/:id/eliminar", to: "publicacions#destroy", as: "eliminar_publicacion"
  get "publicacions/:id/eliminar", to: "publicacions#confirmar_eliminacion", as: "confirmar_eliminacion"
  patch "publicacions/:id/eliminar", to: "publicacions#destroy", as: "eliminar_confirmacion_publicacion_path"
  
  # resources :publicacions
  resources :publicacions do
    resources :comentarios, only: [:create, :destroy]
  end
  resources :publicacions do
    resources :joyas, only: [:create, :destroy, :update]
  end
  resources :chatrooms
  resources :chatrooms do
    resources :mensajes, only: [:create, :destroy]
  end

  get "crear_joya", to: "joyas#nueva_joya"
  post "joya", to: "joyas#create"
  get "joya_creada/:id", to: "joyas#joya_creada", as: "joya_creada"
  patch "joya_creada/:id", to: "joyas#update"
  delete "joya_creada/:id", to: "joyas#destroy", as: "eliminar_joya_creada"
  get "/carrito", to: "carrito#index", as: "carrito_path"
  get "generar_pdf_carrito", to: "carrito#generar_pdf_carrito", as: "generar_pdf_carrito"

  post "solicitud_compra", to: "joyas#solicitud_compra", as: "solicitud_compra"
  patch "joyas/:id/solicitud_compra", to: "joyas#solicitud_compra", as: "solicitud_compra_joya"
  get "solicitudes_compra", to: "publicacions#solicitudes_compra", as: "solicitudes_compra"
  resources :joyas do
    member do
      patch :aceptar_solicitud
      patch :rechazar_solicitud
    end
  end
  post "pagar", to: "carrito#pagar", as: "pagar"

end

app/models/publicacion.rb
# frozen_string_literal: true
class Publicacion < ApplicationRecord
  has_many :joyas, dependent: :destroy
  has_many :usuarios, through: :comentarios
  has_many :comentarios, dependent: :destroy
  validates :codigo, :nombre, :categoria, :precio, :descripcion, :unidad, presence: true
  validates :precio, numericality: { only_integer: true, message: "is not an integer" }
  validates :precio, 
    numericality: {only_integer: true, greater_than_or_equal_to: 0, message: "must be a non-negative integer"}
  mount_uploader :imagen, ImageUploader
end

app/controllers/publicacions_controller.rb
# frozen_string_literal: true
class PublicacionsController < ApplicationController
  def index
    redirect_to(root_path, alert: "No puedes ver publicaciones como invitado, regístrate!") unless current_usuario
      @publicacions = Publicacion.all
  end

  def new
    redirect_to(
      root_path, 
      alert: "Debes ser administrador para crear publicaciones.") unless \
      (current_usuario.admin? || current_usuario.vendedor?)
      @publicacion = Publicacion.new
  end

  def create
    @publicacion = Publicacion.new(publicacion_params)
      if @publicacion.save
        redirect_to(publicacions_path)
      else
        render("new")
      end
  end
    
  def edit
    redirect_to(
      root_path, 
      alert: "Debes ser administrador o dueño de la publicación para editar esta publicación.") unless \
      (current_usuario.admin? || Publicacion.find(params[:id]).vendedor == current_usuario)
      @publicacion = Publicacion.find(params[:id])
  end

  def update
    @publicacion = Publicacion.find(params[:id])
      if @publicacion.update(publicacion_params)
        redirect_to(publicacions_path)
      else
        render("edit")
      end
  end

  def show
    @publicacion = Publicacion.find(params[:id])
    @comentario = Comentario.new
    @comentarios = @publicacion.comentarios 
    @joya = Joya.new
    @joyas = @publicacion.joyas
  end

  def destroy
    @publicacion = Publicacion.find(params[:id])
    @publicacion.destroy
    redirect_to(publicacions_path)
  end

  def confirmar_eliminacion
    redirect_to(
      root_path, 
      alert: "Debes ser administrador para eliminar publicaciones.") unless \
      (current_usuario.admin? || Publicacion.find(params[:id]).vendedor == current_usuario)
      @publicacion = Publicacion.find(params[:id])
  end

  def solicitudes_compra
    if current_usuario.respond_to?(:admin?) && current_usuario.admin? \
      || current_usuario.respond_to?(:vendedor?) && current_usuario.vendedor?
      @solicitudes = Joya.where(estado: "Pendiente")
      @aceptados = Joya.where(estado: "Aceptado")
      @rechazados = Joya.where(estado: "Rechazado")
      @vendidos = Joya.where(estado: "Vendido")
    else
      redirect_to(root_path, alert: "No tienes acceso a esta página.")
    end
  end

  private
      
  def publicacion_params
    params.require(:publicacion).permit(:codigo, :nombre, :categoria, :precio, :descripcion, :unidad, :imagen)
  end

end

app/helpers/publicacions_helper.rb
# frozen_string_literal: true
module PublicacionsHelper
end

app/views/publicacions/confirmar_eliminacion.html.erb
<h1>Confirmar eliminación de la publicación <%= @publicacion.nombre %></h1>

<p>¿Estás seguro que deseas eliminar esta publicación?</p>

<%= form_with(model: @publicacion, url: eliminar_confirmacion_publicacion_path_path(@publicacion), local: true) do |form| %>
  <%= form.hidden_field :_method, value: 'delete' %>
  <%= form.submit 'Eliminar' %>
<% end %>

<%= link_to 'Cancelar', publicacions_path %>

app/views/publicacions/edit.html.erb
<%= stylesheet_link_tag 'register-new', media: 'all', 'data-turbolinks-track': 'reload' %>
<h1 class="titulo has-text-centered is-size-1">Editar Publicación</h1>
<%= form_with(model: @publicacion, url: publicacion_path(@publicacion), local: true) do |form| %>
  <% if @publicacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publicacion.errors.count, "error") %> impidieron guardar esta publicación:</h2>

      <ul>
        <% @publicacion.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

 <div class="field">
    <%= form.label :Codigo %><br>
    <%= form.text_field :codigo, required: true %>
  </div>

  <div class="field">
    <%= form.label :nombre %><br>
    <%= form.text_field :nombre, required: true %>
  </div>

  <div class="field">
    <%= form.label :'Categoría' %><br>
    <% tipos_disponibles = ['a', 'b', 'c'] %>
    <%= form.select :categoria, options_for_select(tipos_disponibles), {},  include_blank: false, required: true %>
  </div>
  
  <div class="field">
    <%= form.label :precio %><br>
    <%= form.number_field :precio, required: true %>
  </div>

  <div class="field">
    <%= form.label :descripción %><br>
    <%= form.text_area :descripcion, rows: 5, required: true %>
  </div>

  <div class="field">
    <%= form.label :'Unidad de Medida' %><br>
    <%= form.text_field :unidad, required: true %>
  </div>

  <div class="field">
    <%= form.label :'Stock' %><br>
    <%= form.text_field :stock, required: true %>
  </div>

  <div class="actions">
    <%= button_tag(type: 'submit', class: 'button is-link') do %>
      Guardar
    <% end %>
  </div>
<% end %>

<br>

<div class="links-container">
  <%= link_to 'Regresar al Listado de Publicaciones', publicacions_path %>
</div>

app/views/publicacions/index.html.erb
<%= stylesheet_link_tag 'publicacions-index', media: 'all', 'data-turbolinks-track': 'reload' %>
<section class="section">
  <div class="container">
    <h1 class="title">Materiales</h1>

    <table class="table is-fullwidth">
      <thead>
        <tr>
          <th>Código</th>
          <th>Nombre</th>
          <th>Categoría</th>
          <th colspan="4"></th>
        </tr>
      </thead>

      <tbody>
        <% @publicacions.each do |publicacion| %>
          <tr>
            <td><%= publicacion.codigo %></td>
            <td><%= publicacion.nombre %></td>
            <td><%= publicacion.categoria %></td>
            <td width="70" height="70"><%= image_tag publicacion.imagen.url(:thumb) if publicacion.imagen? %></td>
            <% if (current_usuario && current_usuario.admin?) %>
              <td><%= link_to 'Editar', edit_publicacion_path(publicacion), class: 'button is-link is-small' %></td>
              <td><%= link_to 'Eliminar', eliminar_publicacion_path(publicacion), method: :delete, data: { confirm: '¿Estás seguro que deseas eliminar esta publicación?' }, class: 'button is-danger is-small' %></td>
              <td><%= link_to 'Ver', publicacion_path(publicacion), class: 'button is-info is-small' %></td>
            <% else %>
              <td><%= link_to 'Ver', publicacion_path(publicacion), class: 'button is-info is-small' %></td>
              <td></td>
              <td></td>
            <% end %>
          </tr>
        <% end %>
      </tbody>
    </table>

    <% if (current_usuario && current_usuario.admin?) || (current_usuario && current_usuario.vendedor?) %>
      <%= link_to 'Agregar material', new_publicacion_path, class: 'button is-link' %>
    <% end %>
  </div>
</section>

app/views/publicacions/new.html.erb
<%= stylesheet_link_tag 'register-new', media: 'all', 'data-turbolinks-track': 'reload' %>
<h1 class="titulo has-text-centered is-size-1">Nuevo material</h1>
<%= form_with(model: @publicacion, url: { action: "create" }, local: true) do |form| %>
  <% if @publicacion.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@publicacion.errors.count, "error") %> impidieron guardar esta publicación:</h2>

      <ul>
        <% @publicacion.errors.full_messages.each do |msg| %>
          <li><%= msg %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :Codigo %><br>
    <%= form.text_field :codigo, required: true %>
  </div>

  <div class="field">
    <%= form.label :nombre %><br>
    <%= form.text_field :nombre, required: true %>
  </div>

  <div class="field">
    <%= form.label :'Categoría' %><br>
    <% tipos_disponibles = ['a', 'b', 'c'] %>
    <%= form.select :categoria, options_for_select(tipos_disponibles), {},  include_blank: false, required: true %>
  </div>
  
  <div class="field">
    <%= form.label :precio %><br>
    <%= form.number_field :precio, required: true %>
  </div>

  <div class="field">
    <%= form.label :descripción %><br>
    <%= form.text_area :descripcion, rows: 5, required: true %>
  </div>

  <div class="field">
    <%= form.label :'Unidad de Medida' %><br>
    <%= form.text_field :unidad, required: true %>
  </div>

  <div class="field">
    <%= form.label :imagen %><br>
    <%= form.file_field :imagen, required: true %>
  </div>

  <div class="field">
    <%= form.label :'Stock Inicial' %><br>
    <%= form.number_field :stock, required: true %>
  </div>


  <div class="actions">
    <%= button_tag(type: 'submit', class: 'button is-link') do %>
      Crear
    <% end %>
  </div>
<% end %>

<br>

<div class="links-container">
  <%= link_to 'Regresar al Listado de Publicaciones', publicacions_path %>
</div>

app/views/publicacions/show.html.erb
<%= stylesheet_link_tag 'publicacions-show', media: 'all', 'data-turbolinks-track': 'reload' %>
<link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.3/css/all.min.css">

<div class="contenedor_publicacion">
  <div class="contenedor_imagen">
    <h2>
      <%= image_tag @publicacion.imagen.url(:thumb), style: "min-width: 400px; min-height: 400px;" if @publicacion.imagen? %>
    </h2>
  </div>

  <div class="contenedor_info">
    <h1 class="titulo has-text-centered is-size-1"><%= @publicacion.nombre %></h1>
    <h2 class="titulo has-text-centered is-size-2"><%= @publicacion.codigo %></h1>
    <h2 class="titulo has-text-centered is-size-2"><%= @publicacion.categoria %></h2>
    <h2 class="titulo has-text-centered is-size-2">$<%= @publicacion.precio %></h2>
    <p class="descripcion"><%= @publicacion.descripcion %></p>

    <div class="container-joyas">
      <div class="box-joyas">
        <div class="joyas-form">
          <%= form_with(model: @joya, url: publicacion_joyas_path(@publicacion), local: true) do |form| %>
            <%= form.number_field :cantidad, placeholder: "Cantidad", style: 'width: 100px; height: 37px;' %> <%= @publicacion.unidad %> <br>
            <%= form.hidden_field :estado, value: "No solicitado" %>
            <%= form.hidden_field :usuario_id, value: current_usuario.id %> 
            <% if current_usuario.joyas.none? { |joya| joya.publicacion.nombre == @publicacion.nombre } %>
              <%= form.submit "Solicitar Material", class: "button is-link" %>
            <% else %> 
              <h3 class="titulo has-text-centered is-size-2"> Ya agregaste este material</h2>
            <% end %>
          <% end %>
        </div>
      </div>
    </div>
  </div>
</div>




<div class="links-container">
  <% if (current_usuario && current_usuario.admin?)  %>
    <%= link_to 'Editar Publicación', edit_publicacion_path(@publicacion), class: "button is-link"%> <br>
  <% end %>
  <%= link_to 'Regresar al Listado de Materiales', publicacions_path %>
</div>

app/views/publicacions/solicitudes_compra.html.erb
<%= stylesheet_link_tag 'solicitudes-compra', media: 'all', 'data-turbolinks-track': 'reload' %>

<div class="solicitudes-container">
  <h1 class="titulo has-text-centered is-size-1">Solicitudes de Compra</h1>

  <% if @solicitudes.any? %>
    <table class="solicitudes-table">
        <thead>
          <tr>
            <th>ID Solicitud</th>
            <th>Joya</th>
            <th>Estado</th>
            <th>Cantidad</th>
            <th>Comprador</th>
            <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
              <th>Vendedor</th>
            <% end %>
          <th>Acciones</th>
        </tr>
      </thead>
      <tbody>
        <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? || current_usuario.respond_to?(:vendedor?) && current_usuario.vendedor? %>
          <% @solicitudes.each do |solicitud| %>
              <tr>
                <% if current_usuario.nombre == solicitud.publicacion.vendedor || current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
                  <td><%= solicitud.id %></td>
                  <td><%= solicitud.publicacion.nombre %></td>
                  <td><%= solicitud.estado %></td>
                  <td><%= solicitud.cantidad %></td>
                  <td><%= solicitud.usuario.nombre %></td>
                    <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
                      <td><%= solicitud.publicacion.vendedor %></td>
                    <% end %>
                  <td>
                    <div class="button-container">
                      <%= button_to "Aceptar", aceptar_solicitud_joya_path(solicitud), method: :patch, class: "button is-success" %>
                      <%= button_to "Rechazar", rechazar_solicitud_joya_path(solicitud), method: :patch, class: "button is-danger" %>
                    </div>
                  </td>
                <% end %>  
              </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No hay solicitudes de compra.</p>
  <% end %>
</div>

<div class="solicitudes-container">
  <h1 class="titulo has-text-centered is-size-1">Solicitudes aceptadas</h1>
  <% if @aceptados.any? %>
    <table class="solicitudes-table">
        <thead>
          <tr>
            <th>ID Solicitud</th>
            <th>Joya</th>
            <th>Estado</th>
            <th>Cantidad</th>
            <th>Comprador</th>
            <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
              <th>Vendedor</th>
            <% end %>
        </tr>
      </thead>
      <tbody>
        <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? || current_usuario.respond_to?(:vendedor?) && current_usuario.vendedor? %>
          <% @aceptados.each do |aceptado| %>
              <tr>
                <% if current_usuario.nombre == aceptado.publicacion.vendedor || current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
                  <td><%= aceptado.id %></td>
                  <td><%= aceptado.publicacion.nombre %></td>
                  <td><%= aceptado.estado %></td>
                  <td><%= aceptado.cantidad %></td>
                  <td><%= aceptado.usuario.nombre %></td>
                    <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
                      <td><%= aceptado.publicacion.vendedor %></td>
                    <% end %>
                <% end %>  
              </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No hay solicitudes aceptadas.</p>
  <% end %>
</div>

<div class="solicitudes-container">
  <h1 class="titulo has-text-centered is-size-1">Solicitudes rechazadas</h1>
  <% if @rechazados.any? %>
    <table class="solicitudes-table">
        <thead>
          <tr>
            <th>ID Solicitud</th>
            <th>Joya</th>
            <th>Estado</th>
            <th>Cantidad</th>
            <th>Comprador</th>
            <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
              <th>Vendedor</th>
            <% end %>
        </tr>
      </thead>
      <tbody>
        <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? || current_usuario.respond_to?(:vendedor?) && current_usuario.vendedor? %>
          <% @rechazados.each do |rechazado| %>
              <tr>
                <% if current_usuario.nombre == rechazado.publicacion.vendedor || current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
                  <td><%= rechazado.id %></td>
                  <td><%= rechazado.publicacion.nombre %></td>
                  <td><%= rechazado.estado %></td>
                  <td><%= rechazado.cantidad %></td>
                  <td><%= rechazado.usuario.nombre %></td>
                    <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
                      <td><%= rechazado.publicacion.vendedor %></td>
                    <% end %>
                <% end %>  
              </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No hay solicitudes rechazadas.</p>
  <% end %>
</div>

<div class="solicitudes-container">
  <h1 class="titulo has-text-centered is-size-1">Ventas</h1>
  <% if @vendidos.any? %>
    <table class="solicitudes-table">
        <thead>
          <tr>
            <th>ID Solicitud</th>
            <th>Joya</th>
            <th>Estado</th>
            <th>Cantidad</th>
            <th>Comprador</th>
            <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
              <th>Vendedor</th>
            <% end %>
        </tr>
      </thead>
      <tbody>
        <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? || current_usuario.respond_to?(:vendedor?) && current_usuario.vendedor? %>
          <% @vendidos.each do |vendido| %>
              <tr>
                <% if current_usuario.nombre == vendido.publicacion.vendedor || current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
                  <td><%= vendido.id %></td>
                  <td><%= vendido.publicacion.nombre %></td>
                  <td><%= vendido.estado %></td>
                  <td><%= vendido.cantidad %></td>
                  <td><%= vendido.usuario.nombre %></td>
                    <% if current_usuario.respond_to?(:admin?) && current_usuario.admin? %>
                      <td><%= vendido.publicacion.vendedor %></td>
                    <% end %>
                <% end %>  
              </tr>
          <% end %>
        <% end %>
      </tbody>
    </table>
  <% else %>
    <p>No hay ventas.</p>
  <% end %>
</div>